# Generated by Django 5.0.7 on 2024-07-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlets", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="outletwine",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="outletwine",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
