databases:
  - name: wineinventorydb
    plan: free
    databaseName: wineinventory
    user: postgres

services:
  - type: web
    plan: free
    name: wineinventory
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn wine_inventory.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wineinventorydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4